### ISSUE TITLE
Micheline INT prim

### ISSUE THREAD

**Issue by Messer4** [blockwatch-cc/tzindex#33]
Hello.
Looks like Micheline INT prim for some numbers is broken. For example if I `PACK` `{ "int": "33"}` by node RPC I got `0021` as result. When MarshalBinary by tzIndex Prim result is `00a100` and node `Could not decode bytes`
Prim example:
```
	prim := &micheline.Prim{
		Type:   micheline.PrimInt,
		OpCode: micheline.T_INT,
		Int:    big.NewInt(33),
	}
```

**Comment by echa** [comment]
Thanks for reporting. Fixed in e4415ac. 

The bug only impacted the binary Zarith encoder and only for numbers between 32 and 63. The binary Zarith decoder properly decodes both the incorrect `00a100` and the correct `0021` representations to BigInt 33. 

Note for everybody who comes here: In the database we exclusively store binary encoded data for contract code, parameters, storage and bigmap updates. The API layer decodes values for Int/Nat/Mutez types as part of each request. Since the Zarith decoder accepts the broken binary format and creates the correct BigInt representation, the API was not affected by this bug. It is not necessary to rebuild the indexer database unless you rely on the correct binary representation in the Tables API (which outputs the raw stored binary data).
