### ISSUE TITLE
Contract NamedBigmaps method returns invalid result

### ISSUE THREAD

**Issue by sskorupski** [blockwatch-cc/tzindex#44]
Hi,

I've noticed that since the commit [Jakarta release](https://github.com/blockwatch-cc/tzindex/commit/37484378f176668365190368d81e8dd9d7b990e4) the method in `etl/model/contract.go#NamedBigmaps` (line 329) has changed :

```go
func (c *Contract) NamedBigmaps(m []*BigmapAlloc) map[string]int64 {
	if len(m) == 0 {
		return nil
	}
	_, sTyp, err := c.LoadType()
	if err != nil {
		return nil
	}
	named := make(map[string]int64)

	// find bigmap typedefs in script
	bigmaps, _ := sTyp.FindOpCodes(micheline.T_BIG_MAP)

	// unpack micheline types into tzgo types for matching
	// this resolves ambiguities from different comb pair expressions
	types := make([]micheline.Typedef, len(bigmaps))
	for i, v := range bigmaps {
		types[i] = micheline.Type{v}.Typedef("")
	}

	// match bigmap allocs to type annotations using type comparison
	for i, v := range m {
		kt, vt := v.GetKeyType().Typedef(""), v.GetValueType().Typedef("")
		var name string
		for _, typ := range types {
			if !typ.Left().Equal(kt) {
				continue
			}
			if !typ.Right().Equal(vt) {
				continue
			}
			name = typ.Name
			// some bigmap types may be reused (different bigmap use the same type)
			// so be carful not overwriting existing matches
			if _, ok := named[name]; !ok {
				break
			}
		}
		// generate a unique name when annots are missing
		if name == "" {
			name = "bigmap_" + strconv.Itoa(i)
		}
		// make sure name is not a duplicate
		if _, ok := named[name]; ok {
			var c int
			for {
				n := name + "_" + strconv.Itoa(c)
				if _, ok := named[n]; !ok {
					name = n
					break
				}
				c++
			}
		}
		named[name] = v.BigmapId
	}
	return named
}
```
More precisely, for an example, I've deployed the [KT1RAdg1ckDd3kgyVcAXbdXGoSvMUxbwV2ty](https://jakartanet.tzkt.io/KT1RAdg1ckDd3kgyVcAXbdXGoSvMUxbwV2ty/storage/) smart contract, containing some bigmaps.

**I've see that the method will return a map where all the keys are `ledger`, `ledger_0`, `ledger_1` instead of the effective names of the bigmap declared in the smart contract**

While debugging I can provide more details:
* The first bigmap is named `ledger`
* Then the loop `for _, typ := range types` always enters in the continue: `if !typ.Left().Equal(kt) { continue }` or `if !typ.Right().Equal(kt) { continue }`, so the name var keeps the previous name and an index is added by `// make sure name is not a duplicate`

Furthermore I don't get the intention about `// match bigmap allocs to type annotations using type comparison` (but I miss some understanding about `type` and `.Typedef("")`): 
* given a smart contract containing two bigmaps with the same key type and value type
* when this match is done,
* then is there a risk that the method returns the first bigmap name matching instead of the expecting one ? 

I have noticed it by working on custom feature I've made on a fork of your project. 
I would be glad to be able to organize a meeting to introduce you this feature and see if the implementation can be integrated in this repository. I could add a pull request, but as I said previously I will be glad to talk you about the feature within a meeting. 

Despite of this issue, thanks for your job ! 
I really appreciate ! 
 
Sébastien

**Comment by echa** [comment]
Thanks for the detailed report. As a matter of fact you should avoid using the same type for multiple bigmaps, in particular when your contract (a) deletes and re-creates bigmaps as part of a contract call or (b) creates new bigmaps on the fly and stores them in a container (map, set, list). All these cases produce unresolvable ambiguities. For static allocated bigmaps you can re-use the same type without issue.

TL;TR

Simple cases like bigmaps created statically on origination are usually OK to identify. The code chance was in response to contracts that create new bigmaps on the fly and keep them in a map. We must reconcile two sources of information here, the storage type tree and the list of bigmap allocations as reported in transaction receipts. In simple cases the order of allocations is the same order that you find when walking the storage type tree in AVL order looking for bigmap-type primitives.

Now, some contracts do not create all their bigmaps on origination and some even create new bigmaps of the same type on request and store them in a container like a map. This breaks the idea that you can match alloc to type based on order of occurrence. Hence, we resort to type matching, but there is a caveat. Since Edo working with types has become much harder because of the infamous comb-pair nightmare (the same Micheline struct/record type can have different representations, in fact Micheline does not even know record types and uses pair trees or comb pairs, i.e. they look like lists but they aren't lists). 

To resolve the type comparison issue we transform the Micheline type into our own type system and along the way repair the comb-pair ambiguities. This is what `.Typedef()` is for.

To answer your questions: 

1. Your contract example resolves just fine https://api.jakarta.tzstats.com/explorer/contract/KT1RAdg1ckDd3kgyVcAXbdXGoSvMUxbwV2ty/script Do you have an example where `ledger_0` and `ledger_1` actually appear in the output?

2. Note that the outer loop in line 349 ranges over `m []*BigmapAlloc`. The algorithm tries to assign actual bigmap allocations to their type definition in order to identify the label that's associated with the type. Say, you defined bigmaps A and B using the same type and your compiler places A before B in the storage type tree. Then the list of observed allocs is [A,B]. Note that bigmap allocs just contain the key and value types, but they lack the type annotation which is on the common Micheline parent node. Now the algorithm finds the first type match with label A and puts it into `named[]`. When processing the second alloc it first finds type A, but since label "A" is already in `named[]`, it continues the search for another type and eventually finds type B.

3. Lets talk about your custom feature (alex@blockwatch.cc) and find out if it fits here or maybe better into TzGo.

**Comment by sskorupski** [comment]
>1.  Your contract example resolves just fine

My apologize, you're right, with a better analysis, I've found that I was building a list of bigmaps where all the item had the same address, that why the `NamedBigmaps` was resolving allways the same name
=> The issue can be closed

2. Thank you for the explanation

> 3. Lets talk about your custom feature

Thank you, I share the good news with my teamates and we will contact you
