### ISSUE TITLE
API

### ISSUE THREAD

**Issue by amzid** [blockwatch-cc/tzindex#5]
I am trying to calculate the part of each delegator in the reward of a specific baker for some cycle.
I was using tzscan for this aim, and now I want to change to tzstats. However, the features that I need either are still missing or are not as straightforward documented as I thought. I need mainly two features:
* The possibility of getting a list of delegators of a baking address for some cycle according to the corresponding snapshot block. The only thing I get from the API is the number of delegators, but not their addresses and respective delegated balance.
* The possibility of getting more precise results for the rewards/income. What I get now is multiples of XTZ (e.g. 124 XTZ) but what I need is e.g. 124.500243 XTZ. This is indeed implemented for staking balances, but not for income info.

I hope I did not oversee these features in the API, otherwise I would be thankful to be able to get these info using tzstats API.

**Comment by echa** [comment]
Hey @amzid I moved the issue over here because it's API related and that's the correct repo for that. The docu does not describe the issue well and I will write a blog post soon.

You should find everything you need in the `snapshot` and `income` tables.

Snapshot keeps all balances of bakers and delegators and their staking relations at each snapshot block. The selected snapshot in a cycle is marked with the flag `is_selected=true`. Here's how you can fetch a delegator list with delegated balances and addresses for payout calculation for a baker (e.g. tz1g8vkmcde6sWKaG2NN9WKzCkDM6Rziq194) at a cycle (e.g. 160, note the call uses the snapshot from 7 cycles before!):

https://api.tzstats.com/tables/snapshot.csv?cycle=153&is_selected=1&delegate=tz1g8vkmcde6sWKaG2NN9WKzCkDM6Rziq194&limit=50000

I added `.csv` to the URL so you get a CSV file. Remove this to retrieve JSON. Note that this list also contains the baker itself (`address==delegate`). That way you know the baker's own `balance` as well as the total `delegated` amount. Each delegate's balance is in the respective `balance` field for a delegate.

To get baker income you retrieve a single line from the income table like:

https://api.tzstats.com/tables/income.csv?cycle=160&address=tz1g8vkmcde6sWKaG2NN9WKzCkDM6Rziq194

The fields `total_income` and `total_lost` are of interest. If nothing was slashes (lost) then the total income is what you can distribute to delegators. If coins were slashed, then you have to adjust the income by the loss of rewards. Slashing affects deposits as well, so you can't just subtract total loss from total income! Here's the formula:

```
actual_income = total_income - lost_accusation_fees - lost_accusation_rewards - lost_revelation_fees - lost_revelation_rewards
```

Note that revelation slashing happens at the end of the cycle following the income, so it's best to do the distribution when rewards get unfrozen to be sure.

Hope this helps. I'm closing this issue, but feel free to respond when you have further questions.
