### ISSUE TITLE
Warning/Errors in tzindex logs

### ISSUE THREAD

**Issue by flaupretre** [blockwatch-cc/tzindex#8]
Hi, I've been running a set of tzindex instances for several weeks now and I first want to thank you for this nice software (some negociation is underway to buy the appropriate licence from you but that's not my part). I just noticed some recurring warning and error messages like : 

2019/12/06 17:30:25.442348 WARN DATA query: op.api.list_account_ops_sent compile=16.003µs journal=56.982µs index=1.908µs scan=35.179963726s total=35.1800287s matched=44 rows, scheduled=249 packs, scanned=249 packs, searched=0 index rows
2019/12/06 17:28:24.387723 WARN DATA query: account.api.list_all_delegates compile=25.381µs journal=168.531µs index=1.129µs scan=2.011291699s total=2.01146634s matched=3960 rows, scheduled=12 packs, scanned=12 packs, searched=0 index rows

or

2019/12/06 17:32:43.266086 ERRO SRVR 863fcfcd443bcda370c33199d40a9684 404 (1305) GET /explorer/account/tz1hobi4RsAeswm9JA7mHB96vqc1eAWRzxDc/op?limit=100 HTTP/1.1 - ReadAccountOps failed (no such account): account not indexed
2019/12/06 17:36:39.710247 ERRO SRVR 7007f203f9493855def955548f26a297 404 (1305) GET /explorer/account/tz1hobi4RsAeswm9JA7mHB96vqc1eAWRzxDc/op?limit=100 HTTP/1.1 - ReadAccountOps failed (no such account): account not indexed
2019/12/06 17:36:39.850212 ERRO SRVR 00607fe14d131124cd2690f24102db57 404 (1305) GET /explorer/account/tz1hobi4RsAeswm9JA7mHB96vqc1eAWRzxDc HTTP/1.1 - ReadAccount failed (no such account): account not indexed

Despite these messages, the program looks fine and keeps indexing new data. Can you please tell me if these messages can be safely ignored or if we should consider them as a symptom of some issue somewhere. Thanks.

**Comment by echa** [comment]
Hey, happy to hear that! We will publish a new version soon.

The warnings are issued by the database layer when queries take longer than a pre-defined amount of time (default 1s, settable with `TZ_DATABASE_LOG_SLOW_QUERIES=duration` or in the config file under key `database.log_slow_queries`).

The origin of these warnings (and slow queries in general) are large table scans. To speed up queries you can configure the indexer to cache more data in memory. Optimal settings depend very much on your use case, default settings are conservative to have a low memory footprint. You can define how much data you like to cache on a per-table basis. The database works with packs as the smallest unit of processing/caching, each pack storing 32k-64k data rows. Here's how to determine cache requirements and set cache config:

1. Inspect database tables with `GET /system/tables` and look for `packs_count` and `index_packs_count`. They indicate the total number of packs in each table. Also look for high values of `packs_bytes_read`, they indicate which tables are hot spots.
2. Then set the number of cached packs close to the number of total packs, this ensures all data is kept in memory. Config file keys are called `database.{table}.cache_size` and `database.{table}_index.cache_size`, ENV vars are `TZ_DATABASE_{TABLE}_CACHE_SIZE` and `TZ_DATABASE_{TABLE}_INDEX_CACHE_SIZE`. Values are in number of packs, not bytes.
3. Monitor container memory usage to avoid swapping. You can also find per-table memory usage  metrics in `GET /system/mem`. Go garbage-collects memory from time to time. You can tune how aggressive GC operates by setting the command line flag `--gogc <num>` (default 20, range 1..100, lower values trigger GC more often).

The 'account not indexed' errors indicate that the indexer has not seen the address on-chain so far. This is a typical error message for wallet-style use cases where the wallet creates a new address, sends a transaction and waits for inclusion on-chain. As long as the tx is not confirmed, the indexer does not know the address. In the future we may add mempool support, so that new addresses and pending operations are indexed as well.

FYI: We will have a new version of both OSS and PRO versions ready soon. There have been a few minor bugs and some new features that may be relevant for you.

**Comment by flaupretre** [comment]
Hi, thanks for this information. I will try to optimize memory using this procedure.
